#include "parameters.h"
#include "platform.h"
void gpio_initial(){
gpio_init(GPIO_DEVICE_ID);
gpio_direction(TXNRX          ,1);
gpio_direction(ENABLE1        ,1);
gpio_direction(RESETB         ,1);
gpio_direction(SYNC_IN        ,1);
gpio_direction(EN_AGC         ,1);
gpio_direction(CTRL_IN3       ,1);
gpio_direction(CTRL_IN2       ,1);
gpio_direction(CTRL_IN1       ,1);
gpio_direction(CTRL_IN0       ,1);
gpio_direction(USER_IO5       ,1);
gpio_direction(USER_IO4       ,1);
gpio_direction(USER_IO3       ,1);
gpio_direction(USER_IO2       ,1);
gpio_direction(USER_IO1       ,1);
gpio_direction(USER_IO0       ,1);
gpio_direction(TX_BAND_SEL    ,1);
gpio_direction(TRX_SW         ,1);
gpio_direction(FDD_TDD_SEL    ,1);
gpio_direction(RX2_BAND_SEL_B ,1);
gpio_direction(RX2_BAND_SEL_A ,1);
gpio_direction(RX1_BAND_SEL_B ,1);
gpio_direction(RX1_BAND_SEL_A ,1);
gpio_direction(VCO_CAL_SELECT ,1);
gpio_direction(REF_SELECT     ,1);

gpio_set_value(TXNRX          ,1);
gpio_set_value(ENABLE1        ,1);
gpio_set_value(RESETB         ,1);
gpio_set_value(SYNC_IN        ,1);
gpio_set_value(EN_AGC         ,0);
gpio_set_value(CTRL_IN3       ,0);
gpio_set_value(CTRL_IN2       ,0);
gpio_set_value(CTRL_IN1       ,0);
gpio_set_value(CTRL_IN0       ,0);
gpio_set_value(USER_IO5       ,0);
gpio_set_value(USER_IO4       ,0);
gpio_set_value(USER_IO3       ,0);
gpio_set_value(USER_IO2       ,0);
gpio_set_value(USER_IO1       ,0);
gpio_set_value(USER_IO0       ,0);
gpio_set_value(TX_BAND_SEL    ,0);
gpio_set_value(TRX_SW         ,1);
gpio_set_value(FDD_TDD_SEL    ,1);
gpio_set_value(RX2_BAND_SEL_B ,0);
gpio_set_value(RX2_BAND_SEL_A ,1);
gpio_set_value(RX1_BAND_SEL_B ,1);
gpio_set_value(RX1_BAND_SEL_A ,1);
gpio_set_value(VCO_CAL_SELECT ,1);
gpio_set_value(REF_SELECT     ,0);
}
