#ifndef AD9361_TEST2_NET_CONFIG_H_
#define AD9361_TEST2_NET_CONFIG_H_

#include "app_config.h"

#define NET_UDP_PORT 5001U

#define NET_DATA_MAGIC 0x4E455430UL
#define NET_ACK_MAGIC 0x41434B30UL

#define NET_DATA_FLAG_RESET 0x8000U
#define NET_DATA_FLAG_NO_CRC 0x4000U
#define NET_DATA_FLAG_OFDM_LEGACY 0x2000U
#define NET_DATA_SESSION_MASK 0x1FFFU

#define NET_TX_QUEUE_DEPTH 32U
#define NET_VERBOSE_PACKET_LOG 0
#define NET_VALIDATE_PAYLOAD_CRC 1U
#define NET_STATS_PRINT_INTERVAL_US 1000000ULL

#define NET_OFDM_TARGET_PSDU_BYTES 3000U
#define NET_OFDM_MAX_DMA_WORDS 1022U
#define NET_OFDM_MAX_PSDU_BYTES (NET_OFDM_MAX_DMA_WORDS * 8U)

#define NET_AGG_BLOCK_BYTES NET_OFDM_TARGET_PSDU_BYTES
#define NET_AGG_BLOCK_COUNT (TX_TRANSFER_LENGTH_BYTES / NET_AGG_BLOCK_BYTES)
#define NET_AGG_MIN_FLUSH_BYTES (NET_AGG_BLOCK_BYTES / 2U)
#define NET_AGG_FLUSH_TIMEOUT_US 15000ULL
#define NET_AGG_IDLE_FLUSH_TIMEOUT_US 100000ULL
#define NET_DMA_QUEUE_CAPACITY NET_AGG_BLOCK_COUNT

#define NET_COMPLETED_HISTORY_DEPTH 128U
#define NET_MAX_RECOMMENDED_WINDOW_SIZE 64U
#define NET_ACK_COALESCE_ENABLE 1U
#define NET_ACK_COALESCE_PACKET_COUNT 8U
#define NET_ACK_COALESCE_TIMEOUT_US 1000ULL
#define NET_INPUT_POLL_BUDGET 32U

#define NET_LOOPBACK_S2MM_DEBUG_ENABLE 1U
#define NET_LOOPBACK_S2MM_LOG_FIRST_BLOCKS 16U
#define NET_LOOPBACK_S2MM_LOG_INTERVAL_BLOCKS 128U
#define NET_LOOPBACK_S2MM_DUMP_WORDS 8U
#define NET_LOOPBACK_S2MM_WAIT_LOG_US 1000000ULL

#define NET_TX_SLOT_CAPACITY_BYTES (TX_TRANSFER_LENGTH_BYTES / NET_TX_QUEUE_DEPTH)
#define NET_MAX_PAYLOAD_BYTES NET_AGG_BLOCK_BYTES

#if TX_TRANSFER_LENGTH_BYTES == 0U
#error "TX_TRANSFER_LENGTH_BYTES must be non-zero. Check TX_BUFFER_WORD_COUNT integer arithmetic."
#endif

#if NET_AGG_BLOCK_COUNT == 0U
#error "NET_AGG_BLOCK_COUNT must be non-zero. TX buffer must be at least one aggregation block."
#endif

#if NET_MAX_PAYLOAD_BYTES == 0U
#error "NET_MAX_PAYLOAD_BYTES must be non-zero. Check NET_AGG_BLOCK_BYTES."
#endif

#if NET_AGG_BLOCK_BYTES > NET_OFDM_MAX_PSDU_BYTES
#error "NET_AGG_BLOCK_BYTES exceeds tx_intf OFDM auto-start frame length limit."
#endif

#if (NET_AGG_BLOCK_BYTES % 8U) != 0U
#error "NET_AGG_BLOCK_BYTES must be 8-byte aligned for AXI DMA MM2S."
#endif

#if NET_AGG_BLOCK_BYTES > 131071U
#error "NET_AGG_BLOCK_BYTES exceeds AXI DMA simple transfer length width limit."
#endif

typedef enum {
    NET_ACK_STATUS_OK = 0,
    NET_ACK_STATUS_BAD_MAGIC = 1,
    NET_ACK_STATUS_BAD_LENGTH = 2,
    NET_ACK_STATUS_BAD_CHECKSUM = 3,
    NET_ACK_STATUS_BUSY = 4,
    NET_ACK_STATUS_DMA_ERROR = 5,
    NET_ACK_STATUS_PENDING = 6
} net_ack_status_t;

#endif /* AD9361_TEST2_NET_CONFIG_H_ */
