#ifndef AD9361_TEST2_NET_CONFIG_H_
#define AD9361_TEST2_NET_CONFIG_H_

#include "app_config.h"

#define NET_UDP_PORT 5001U

#define NET_DATA_MAGIC 0x4E455430UL
#define NET_ACK_MAGIC 0x41434B30UL

#define NET_MAX_PAYLOAD_BYTES TX_TRANSFER_LENGTH_BYTES
#define NET_MAX_FRAME_BYTES TX_TRANSFER_LENGTH_BYTES

typedef enum {
    NET_ACK_STATUS_OK = 0,
    NET_ACK_STATUS_BAD_MAGIC = 1,
    NET_ACK_STATUS_BAD_LENGTH = 2,
    NET_ACK_STATUS_BAD_CHECKSUM = 3,
    NET_ACK_STATUS_BUSY = 4,
    NET_ACK_STATUS_DMA_ERROR = 5
} net_ack_status_t;

#endif /* AD9361_TEST2_NET_CONFIG_H_ */
