#ifndef AD9361_TEST2_NET_CONFIG_H_
#define AD9361_TEST2_NET_CONFIG_H_

#include "app_config.h"

#define NET_UDP_PORT 5001U

#define NET_DATA_MAGIC 0x4E455430UL
#define NET_ACK_MAGIC 0x41434B30UL

#define NET_TX_QUEUE_DEPTH 32U
#define NET_VERBOSE_PACKET_LOG 0
#define NET_STATS_PRINT_INTERVAL_US 1000000ULL

#define NET_AGG_ENABLE 1U
#define NET_AGG_BLOCK_BYTES (16U * 1024U)
#define NET_AGG_BLOCK_COUNT (TX_TRANSFER_LENGTH_BYTES / NET_AGG_BLOCK_BYTES)
#define NET_AGG_MIN_FLUSH_BYTES (NET_AGG_BLOCK_BYTES / 2U)
#define NET_AGG_FLUSH_TIMEOUT_US 15000ULL
#define NET_AGG_IDLE_FLUSH_TIMEOUT_US 100000ULL
#define NET_DMA_QUEUE_CAPACITY NET_AGG_BLOCK_COUNT

#define NET_COMPLETED_HISTORY_DEPTH 128U
#define NET_MAX_RECOMMENDED_WINDOW_SIZE 64U
#define NET_DEFAULT_CHUNK_SIZE_BYTES 1456U
#define NET_BUSY_RETRY_DELAY_MS 2U
#define NET_ACK_COALESCE_ENABLE 1U
#define NET_ACK_COALESCE_PACKET_COUNT 8U
#define NET_ACK_COALESCE_TIMEOUT_US 1000ULL
#define NET_CRC32_USE_TABLE 1U
#define NET_INPUT_POLL_BUDGET 32U
#define NET_STRICT_IN_ORDER_RX 1U

#define NET_TX_SLOT_CAPACITY_BYTES (TX_TRANSFER_LENGTH_BYTES / NET_TX_QUEUE_DEPTH)
#define NET_MAX_PAYLOAD_BYTES NET_TX_SLOT_CAPACITY_BYTES
#define NET_MAX_FRAME_BYTES NET_AGG_BLOCK_BYTES

typedef enum {
    NET_ACK_STATUS_OK = 0,
    NET_ACK_STATUS_BAD_MAGIC = 1,
    NET_ACK_STATUS_BAD_LENGTH = 2,
    NET_ACK_STATUS_BAD_CHECKSUM = 3,
    NET_ACK_STATUS_BUSY = 4,
    NET_ACK_STATUS_DMA_ERROR = 5,
    NET_ACK_STATUS_PENDING = 6
} net_ack_status_t;

#endif /* AD9361_TEST2_NET_CONFIG_H_ */
